In [1]:
import numpy as np

### Data types & Attributes

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

**Create a DataFrame from a NumPy array**

In [14]:
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

### Creating arrays

In [15]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
range_array= np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[1, 9, 8, 1, 7],
       [1, 7, 4, 6, 7],
       [3, 9, 5, 3, 5]])

In [20]:
np.random.random(size=(5,3))

array([[0.62619742, 0.60587276, 0.09736382],
       [0.50279324, 0.50915112, 0.33508427],
       [0.73453731, 0.0523254 , 0.58688078],
       [0.3843806 , 0.92872189, 0.57209462],
       [0.45148045, 0.60635201, 0.3191197 ]])

In [21]:
np.random.rand(5,3)

array([[0.95648022, 0.12204877, 0.81986654],
       [0.46856817, 0.94759113, 0.08099144],
       [0.40212032, 0.97991651, 0.34103988],
       [0.12194277, 0.35209139, 0.12609667],
       [0.85145738, 0.72500022, 0.89764219]])

**Generate same random numbers when sharing the notebook**

In [22]:
np.random.seed(seed=0)
random_array_1=np.random.randint(0,10,size=(3,5))
random_array_1

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

### Viewing arrays and matrices

In [23]:
np.unique(random_array_1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1[0]

1

In [28]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [31]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [37]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [50]:
a4[:,:,:,:1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])